-- MySQL Script generated by MySQL Workbench
-- Fri May 20 09:11:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema assetingdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assetingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assetingdb` DEFAULT CHARACTER SET utf8 ;
USE `assetingdb` ;

-- -----------------------------------------------------
-- Table `assetingdb`.`escritorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`escritorio` (
  `cod_escritorio` INT(11) NOT NULL AUTO_INCREMENT,
  `morada` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `helpdesk` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_escritorio`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`tipo_computador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`tipo_computador` (
  `cod_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cod_tipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`conta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `grupo` VARCHAR(20) NOT NULL,
  `cod_escritorio` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`computador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`computador` (
  `nr_serie` VARCHAR(30) NOT NULL,
  `cod_escritorio` INT(11) NULL DEFAULT NULL,
  `cod_tipo` INT(11) NULL DEFAULT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `modelo` VARCHAR(20) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `so` VARCHAR(20) NULL DEFAULT NULL,
  `cpu` VARCHAR(20) NULL DEFAULT NULL,
  `ram` INT(11) NULL DEFAULT NULL,
  `hdd` INT(11) NULL DEFAULT NULL,
  `garantia` DATETIME NULL DEFAULT NULL,
  `data_instalacao` DATETIME NULL DEFAULT NULL,
  `fim_emprestimo` DATETIME NULL DEFAULT NULL,
  `aviso` TINYINT(4) NULL DEFAULT 0,
  `cod_utilizador` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`nr_serie`),
  INDEX `cod_utilizador` (`cod_utilizador` ASC) VISIBLE,
  INDEX `cod_escritorio` (`cod_escritorio` ASC) VISIBLE,
  INDEX `cod_tipo` (`cod_tipo` ASC) VISIBLE,
  CONSTRAINT `cod_escritorio`
    FOREIGN KEY (`cod_escritorio`)
    REFERENCES `assetingdb`.`escritorio` (`cod_escritorio`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `cod_tipo`
    FOREIGN KEY (`cod_tipo`)
    REFERENCES `assetingdb`.`tipo_computador` (`cod_tipo`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `cod_utilizador`
    FOREIGN KEY (`cod_utilizador`)
    REFERENCES `assetingdb`.`conta` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`tipo_rede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`tipo_rede` (
  `cod_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`disp_rede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`disp_rede` (
  `nr_serie` VARCHAR(30) NOT NULL,
  `cod_escritorio` INT(11) NULL DEFAULT NULL,
  `cod_tipo` INT(11) NULL DEFAULT NULL,
  `fabricante` VARCHAR(20) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `ipv4` VARCHAR(15) NULL DEFAULT NULL,
  `ipv6` VARCHAR(39) NULL DEFAULT NULL,
  `manutencao` DATE NULL DEFAULT NULL,
  `nota` VARCHAR(100) NULL DEFAULT NULL,
  `aviso` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`nr_serie`),
  INDEX `cod_escritorio` (`cod_escritorio` ASC) VISIBLE,
  INDEX `cod_tipo` (`cod_tipo` ASC) VISIBLE,
  CONSTRAINT `disp_rede_ibfk_1`
    FOREIGN KEY (`cod_escritorio`)
    REFERENCES `assetingdb`.`escritorio` (`cod_escritorio`),
  CONSTRAINT `disp_rede_ibfk_2`
    FOREIGN KEY (`cod_tipo`)
    REFERENCES `assetingdb`.`tipo_rede` (`cod_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`tipo_moveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`tipo_moveis` (
  `cod_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_tipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`equip_moveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`equip_moveis` (
  `nr_serie` VARCHAR(20) NOT NULL,
  `cod_escritorio` INT(11) NULL DEFAULT NULL,
  `username` INT(11) NULL DEFAULT NULL,
  `cod_tipo` INT(11) NULL DEFAULT NULL,
  `marca` VARCHAR(20) NULL DEFAULT NULL,
  `modelo` VARCHAR(20) NULL DEFAULT NULL,
  `contacto` VARCHAR(9) NULL DEFAULT NULL,
  `imei1` VARCHAR(45) NULL DEFAULT NULL,
  `imei2` VARCHAR(45) NULL DEFAULT NULL,
  `data_entrega` DATE NULL DEFAULT NULL,
  `garantia` DATE NULL DEFAULT NULL,
  `fim_emprestimo` DATE NULL DEFAULT NULL,
  `nota` VARCHAR(100) NULL DEFAULT NULL,
  `aviso` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`nr_serie`),
  INDEX `cod_escritorio` (`cod_escritorio` ASC) VISIBLE,
  INDEX `username` (`username` ASC) VISIBLE,
  INDEX `cod_tipo` (`cod_tipo` ASC) VISIBLE,
  CONSTRAINT `equip_moveis_ibfk_1`
    FOREIGN KEY (`cod_escritorio`)
    REFERENCES `assetingdb`.`escritorio` (`cod_escritorio`),
  CONSTRAINT `equip_moveis_ibfk_2`
    FOREIGN KEY (`username`)
    REFERENCES `assetingdb`.`conta` (`id`),
  CONSTRAINT `equip_moveis_ibfk_3`
    FOREIGN KEY (`cod_tipo`)
    REFERENCES `assetingdb`.`tipo_moveis` (`cod_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`tipo_servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`tipo_servidor` (
  `cod_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`servidor` (
  `nr_serie` VARCHAR(30) NOT NULL,
  `cod_escritorio` INT(11) NULL DEFAULT NULL,
  `cod_tipo` INT(11) NULL DEFAULT NULL,
  `fabricante` VARCHAR(20) NULL DEFAULT NULL,
  `modelo` VARCHAR(20) NULL DEFAULT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `so` VARCHAR(20) NULL DEFAULT NULL,
  `cpu` VARCHAR(20) NULL DEFAULT NULL,
  `ram` VARCHAR(20) NULL DEFAULT NULL,
  `hdd` VARCHAR(20) NULL DEFAULT NULL,
  `nic` VARCHAR(30) NULL DEFAULT NULL,
  `ipv4` VARCHAR(15) NULL DEFAULT NULL,
  `ipv6` VARCHAR(39) NULL DEFAULT NULL,
  `garantia` DATE NULL DEFAULT NULL,
  `manutencao` DATE NULL DEFAULT NULL,
  `outro` VARCHAR(100) NULL DEFAULT NULL,
  `aviso` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`nr_serie`),
  INDEX `cod_escritorio` (`cod_escritorio` ASC) VISIBLE,
  INDEX `cod_tipo` (`cod_tipo` ASC) VISIBLE,
  CONSTRAINT `servidor_ibfk_1`
    FOREIGN KEY (`cod_escritorio`)
    REFERENCES `assetingdb`.`escritorio` (`cod_escritorio`),
  CONSTRAINT `servidor_ibfk_2`
    FOREIGN KEY (`cod_tipo`)
    REFERENCES `assetingdb`.`tipo_servidor` (`cod_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`tipo_software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`tipo_software` (
  `cod_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_tipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`tipo_licenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`tipo_licenca` (
  `cod_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_tipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`software` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nr_serie` VARCHAR(45) NULL DEFAULT NULL,
  `cod_tipo_software` INT(11) NULL DEFAULT NULL,
  `cod_tipo_licenca` INT(11) NULL DEFAULT NULL,
  `nr_serie_computador` VARCHAR(30) NULL DEFAULT NULL,
  `nr_serie_servidor` VARCHAR(30) NULL DEFAULT NULL,
  `fabricante` VARCHAR(20) NULL DEFAULT NULL,
  `versao` VARCHAR(20) NULL DEFAULT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `chave` VARCHAR(45) NULL DEFAULT NULL,
  `validade` DATE NULL DEFAULT NULL,
  `nota` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nr_serie` (`nr_serie` ASC) VISIBLE,
  INDEX `cod_tipo_software` (`cod_tipo_software` ASC) VISIBLE,
  INDEX `cod_tipo_licenca` (`cod_tipo_licenca` ASC) VISIBLE,
  INDEX `nr_serie_computador` (`nr_serie_computador` ASC) VISIBLE,
  INDEX `nr_serie_servidor` (`nr_serie_servidor` ASC) VISIBLE,
  CONSTRAINT `software_ibfk_1`
    FOREIGN KEY (`cod_tipo_software`)
    REFERENCES `assetingdb`.`tipo_software` (`cod_tipo`),
  CONSTRAINT `software_ibfk_2`
    FOREIGN KEY (`cod_tipo_licenca`)
    REFERENCES `assetingdb`.`tipo_licenca` (`cod_tipo`),
  CONSTRAINT `software_ibfk_3`
    FOREIGN KEY (`nr_serie_computador`)
    REFERENCES `assetingdb`.`computador` (`nr_serie`),
  CONSTRAINT `software_ibfk_4`
    FOREIGN KEY (`nr_serie_servidor`)
    REFERENCES `assetingdb`.`servidor` (`nr_serie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`token` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(255) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`utilizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`utilizador` (
  `email` VARCHAR(45) NOT NULL,
  `cod_escritorio` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(16) NOT NULL,
  `username` INT(11) NULL DEFAULT NULL,
  `telemovel` INT(11) NULL DEFAULT NULL,
  `morada` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`email`),
  INDEX `cod_escritorio` (`cod_escritorio` ASC) VISIBLE,
  INDEX `username` (`username` ASC) VISIBLE,
  CONSTRAINT `utilizador_ibfk_1`
    FOREIGN KEY (`cod_escritorio`)
    REFERENCES `assetingdb`.`escritorio` (`cod_escritorio`),
  CONSTRAINT `utilizador_ibfk_2`
    FOREIGN KEY (`username`)
    REFERENCES `assetingdb`.`conta` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assetingdb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetingdb`.`veiculo` (
  `matricula` VARCHAR(8) NOT NULL,
  `cod_escritorio` INT(11) NULL DEFAULT NULL,
  `marca` VARCHAR(20) NULL DEFAULT NULL,
  `modelo` VARCHAR(20) NULL DEFAULT NULL,
  `cor` VARCHAR(20) NULL DEFAULT NULL,
  `vin` VARCHAR(45) NULL DEFAULT NULL,
  `garantia` DATE NULL DEFAULT NULL,
  `nota` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `cod_escritorio` (`cod_escritorio` ASC) VISIBLE,
  CONSTRAINT `veiculo_ibfk_1`
    FOREIGN KEY (`cod_escritorio`)
    REFERENCES `assetingdb`.`escritorio` (`cod_escritorio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
